### ISSUE TITLE
CI failures caused by ngcc_soec notebook

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples-pse#150]
## Long runtimes

![image](https://user-images.githubusercontent.com/48035537/193645511-0d060081-6637-43d7-a7e4-54a59b7c0928.png)

## Solver failures

![image](https://user-images.githubusercontent.com/48035537/193658433-741da48b-eb71-4b0d-8f71-5ab6f7c6d285.png)

**Comment by eslickj** [comment]
Sorry, just noticed this issue.  Is it new?  I can take a look, but would it be better to just wait for the new costing framework?  Since this example saves time by loading saved model states, sometimes changes to core models will break things like this and it helps to delete the saved states and rebuild them.
